# Generated by Django 4.1 on 2022-10-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='item_pics'),
        ),
    ]
