# Generated by Django 4.1 on 2022-10-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=20)),
                ('subject', models.CharField(max_length=15)),
                ('message', models.TextField(max_length=150)),
            ],
        ),
        migrations.RenameModel(
            old_name='Contact',
            new_name='Order',
        ),
    ]
