# Generated by Django 4.1 on 2022-10-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_contact_form_rename_contact_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_form',
        ),
    ]
